# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/nubia/nx609j/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/nubia/nx609j/proprietary/bin/wfdservice:system/bin/wfdservice \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_0.bin:system/etc/firmware/aw22xxx_cfg_0.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_1.bin:system/etc/firmware/aw22xxx_cfg_1.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_10.bin:system/etc/firmware/aw22xxx_cfg_10.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_11.bin:system/etc/firmware/aw22xxx_cfg_11.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_12.bin:system/etc/firmware/aw22xxx_cfg_12.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_13.bin:system/etc/firmware/aw22xxx_cfg_13.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_14.bin:system/etc/firmware/aw22xxx_cfg_14.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_15.bin:system/etc/firmware/aw22xxx_cfg_15.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_16.bin:system/etc/firmware/aw22xxx_cfg_16.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_17.bin:system/etc/firmware/aw22xxx_cfg_17.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_18.bin:system/etc/firmware/aw22xxx_cfg_18.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_19.bin:system/etc/firmware/aw22xxx_cfg_19.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_1a.bin:system/etc/firmware/aw22xxx_cfg_1a.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_1b.bin:system/etc/firmware/aw22xxx_cfg_1b.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_1c.bin:system/etc/firmware/aw22xxx_cfg_1c.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_1d.bin:system/etc/firmware/aw22xxx_cfg_1d.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_1e.bin:system/etc/firmware/aw22xxx_cfg_1e.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_1f.bin:system/etc/firmware/aw22xxx_cfg_1f.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_2.bin:system/etc/firmware/aw22xxx_cfg_2.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_20.bin:system/etc/firmware/aw22xxx_cfg_20.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_21.bin:system/etc/firmware/aw22xxx_cfg_21.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_22.bin:system/etc/firmware/aw22xxx_cfg_22.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_23.bin:system/etc/firmware/aw22xxx_cfg_23.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_24.bin:system/etc/firmware/aw22xxx_cfg_24.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_25.bin:system/etc/firmware/aw22xxx_cfg_25.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_26.bin:system/etc/firmware/aw22xxx_cfg_26.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_27.bin:system/etc/firmware/aw22xxx_cfg_27.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_28.bin:system/etc/firmware/aw22xxx_cfg_28.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_29.bin:system/etc/firmware/aw22xxx_cfg_29.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_2a.bin:system/etc/firmware/aw22xxx_cfg_2a.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_2b.bin:system/etc/firmware/aw22xxx_cfg_2b.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_2c.bin:system/etc/firmware/aw22xxx_cfg_2c.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_3.bin:system/etc/firmware/aw22xxx_cfg_3.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_33.bin:system/etc/firmware/aw22xxx_cfg_33.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_4.bin:system/etc/firmware/aw22xxx_cfg_4.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_5.bin:system/etc/firmware/aw22xxx_cfg_5.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_6.bin:system/etc/firmware/aw22xxx_cfg_6.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_7.bin:system/etc/firmware/aw22xxx_cfg_7.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_8.bin:system/etc/firmware/aw22xxx_cfg_8.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_9.bin:system/etc/firmware/aw22xxx_cfg_9.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_a.bin:system/etc/firmware/aw22xxx_cfg_a.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_b.bin:system/etc/firmware/aw22xxx_cfg_b.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_c.bin:system/etc/firmware/aw22xxx_cfg_c.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_d.bin:system/etc/firmware/aw22xxx_cfg_d.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_e.bin:system/etc/firmware/aw22xxx_cfg_e.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_cfg_f.bin:system/etc/firmware/aw22xxx_cfg_f.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/aw22xxx_fw.bin:system/etc/firmware/aw22xxx_fw.bin \
    vendor/nubia/nx609j/proprietary/etc/firmware/tas2555_uCDSP.bin:system/etc/firmware/tas2555_uCDSP.bin \
    vendor/nubia/nx609j/proprietary/etc/init/wfdservice.rc:system/etc/init/wfdservice.rc \
    vendor/nubia/nx609j/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/nubia/nx609j/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/nubia/nx609j/proprietary/etc/permissions/com.qti.snapdragon.sdk.display.xml:system/etc/permissions/com.qti.snapdragon.sdk.display.xml \
    vendor/nubia/nx609j/proprietary/etc/permissions/com.qualcomm.qti.imscmservice.xml:system/etc/permissions/com.qualcomm.qti.imscmservice.xml \
    vendor/nubia/nx609j/proprietary/etc/permissions/com.qualcomm.qti.imscmservice_1_1.xml:system/etc/permissions/com.qualcomm.qti.imscmservice_1_1.xml \
    vendor/nubia/nx609j/proprietary/etc/permissions/privapp-permissions-qti.xml:system/etc/permissions/privapp-permissions-qti.xml \
    vendor/nubia/nx609j/proprietary/etc/permissions/qti-vzw-ims-internal.xml:system/etc/permissions/qti-vzw-ims-internal.xml \
    vendor/nubia/nx609j/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/nubia/nx609j/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/nubia/nx609j/proprietary/etc/permissions/qti_telephony_common.xml:system/etc/permissions/qti_telephony_common.xml \
    vendor/nubia/nx609j/proprietary/etc/permissions/vendor-qti-hardware-alarm.xml:system/etc/permissions/vendor-qti-hardware-alarm.xml \
    vendor/nubia/nx609j/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/nubia/nx609j/proprietary/etc/wfdconfig.xml:system/etc/wfdconfig.xml \
    vendor/nubia/nx609j/proprietary/etc/wfdconfig1280_720.xml:system/etc/wfdconfig1280_720.xml \
    vendor/nubia/nx609j/proprietary/etc/wfdconfig640_480.xml:system/etc/wfdconfig640_480.xml \
    vendor/nubia/nx609j/proprietary/etc/wfdconfig800_480.xml:system/etc/wfdconfig800_480.xml \
    vendor/nubia/nx609j/proprietary/etc/wfdconfig960_540.xml:system/etc/wfdconfig960_540.xml \
    vendor/nubia/nx609j/proprietary/etc/wfdconfigsink.xml:system/etc/wfdconfigsink.xml \
    vendor/nubia/nx609j/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/nubia/nx609j/proprietary/framework/dpm.jar:system/framework/dpm.jar \
    vendor/nubia/nx609j/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/nubia/nx609j/proprietary/framework/embmslibrary.jar:system/framework/embmslibrary.jar \
    vendor/nubia/nx609j/proprietary/framework/izat.xt.srv.jar:system/framework/izat.xt.srv.jar \
    vendor/nubia/nx609j/proprietary/lib/com.qualcomm.qti.ant@1.0.so:system/lib/com.qualcomm.qti.ant@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/com.qualcomm.qti.bluetooth_audio@1.0.so:system/lib/com.qualcomm.qti.bluetooth_audio@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/com.qualcomm.qti.imscmservice@1.0.so:system/lib/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/com.qualcomm.qti.imscmservice@1.1.so:system/lib/com.qualcomm.qti.imscmservice@1.1.so \
    vendor/nubia/nx609j/proprietary/lib/com.qualcomm.qti.wifidisplayhal@1.0.so:system/lib/com.qualcomm.qti.wifidisplayhal@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/hw/sensors.msm8998.so:system/lib/hw/sensors.msm8998.so \
    vendor/nubia/nx609j/proprietary/lib/lib-imscamera.so:system/lib/lib-imscamera.so \
    vendor/nubia/nx609j/proprietary/lib/lib-imsvideocodec.so:system/lib/lib-imsvideocodec.so \
    vendor/nubia/nx609j/proprietary/lib/lib-imsvt.so:system/lib/lib-imsvt.so \
    vendor/nubia/nx609j/proprietary/lib/lib-imsvtextutils.so:system/lib/lib-imsvtextutils.so \
    vendor/nubia/nx609j/proprietary/lib/lib-imsvtutils.so:system/lib/lib-imsvtutils.so \
    vendor/nubia/nx609j/proprietary/lib/libNubiaImageAlgorithm.so:system/lib/libNubiaImageAlgorithm.so \
    vendor/nubia/nx609j/proprietary/lib/libantradio.so:system/lib/libantradio.so \
    vendor/nubia/nx609j/proprietary/lib/libarcsoft_beautyshot.so:system/lib/libarcsoft_beautyshot.so \
    vendor/nubia/nx609j/proprietary/lib/libarcsoft_beautyshot_image_algorithm.so:system/lib/libarcsoft_beautyshot_image_algorithm.so \
    vendor/nubia/nx609j/proprietary/lib/libarcsoft_beautyshot_video_algorithm.so:system/lib/libarcsoft_beautyshot_video_algorithm.so \
    vendor/nubia/nx609j/proprietary/lib/libarcsoft_high_dynamic_range.so:system/lib/libarcsoft_high_dynamic_range.so \
    vendor/nubia/nx609j/proprietary/lib/libarcsoft_low_light_shot.so:system/lib/libarcsoft_low_light_shot.so \
    vendor/nubia/nx609j/proprietary/lib/libarcsoft_night_shot.so:system/lib/libarcsoft_night_shot.so \
    vendor/nubia/nx609j/proprietary/lib/libarcsoft_picauto.so:system/lib/libarcsoft_picauto.so \
    vendor/nubia/nx609j/proprietary/lib/libdiag_system.so:system/lib/libdiag_system.so \
    vendor/nubia/nx609j/proprietary/lib/libimscamera_jni.so:system/lib/libimscamera_jni.so \
    vendor/nubia/nx609j/proprietary/lib/libimsmedia_jni.so:system/lib/libimsmedia_jni.so \
    vendor/nubia/nx609j/proprietary/lib/liblocationservice_jni.so:system/lib/liblocationservice_jni.so \
    vendor/nubia/nx609j/proprietary/lib/libmiracast.so:system/lib/libmiracast.so \
    vendor/nubia/nx609j/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/nubia/nx609j/proprietary/lib/libmmcamera_faceproc2.so:system/lib/libmmcamera_faceproc2.so \
    vendor/nubia/nx609j/proprietary/lib/libmmcamera_nubiacustpro.so:system/lib/libmmcamera_nubiacustpro.so \
    vendor/nubia/nx609j/proprietary/lib/libnubia_effect.so:system/lib/libnubia_effect.so \
    vendor/nubia/nx609j/proprietary/lib/libqdMetaData.system.so:system/lib/libqdMetaData.system.so \
    vendor/nubia/nx609j/proprietary/lib/libqti-at.so:system/lib/libqti-at.so \
    vendor/nubia/nx609j/proprietary/lib/libqti-perfd-client_system.so:system/lib/libqti-perfd-client_system.so \
    vendor/nubia/nx609j/proprietary/lib/libqti-util_system.so:system/lib/libqti-util_system.so \
    vendor/nubia/nx609j/proprietary/lib/libqti_performance.so:system/lib/libqti_performance.so \
    vendor/nubia/nx609j/proprietary/lib/librcc.so:system/lib/librcc.so \
    vendor/nubia/nx609j/proprietary/lib/libsdm-disp-apis.so:system/lib/libsdm-disp-apis.so \
    vendor/nubia/nx609j/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/nubia/nx609j/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
    vendor/nubia/nx609j/proprietary/lib/libstagefright_soft_qtiflacdec.so:system/lib/libstagefright_soft_qtiflacdec.so \
    vendor/nubia/nx609j/proprietary/lib/libtrueportrait.so:system/lib/libtrueportrait.so \
    vendor/nubia/nx609j/proprietary/lib/libtruescanner.so:system/lib/libtruescanner.so \
    vendor/nubia/nx609j/proprietary/lib/libwfdavenhancements.so:system/lib/libwfdavenhancements.so \
    vendor/nubia/nx609j/proprietary/lib/libwfdcodecv4l2.so:system/lib/libwfdcodecv4l2.so \
    vendor/nubia/nx609j/proprietary/lib/libwfdcommonutils.so:system/lib/libwfdcommonutils.so \
    vendor/nubia/nx609j/proprietary/lib/libwfdconfigutils.so:system/lib/libwfdconfigutils.so \
    vendor/nubia/nx609j/proprietary/lib/libwfdmminterface.so:system/lib/libwfdmminterface.so \
    vendor/nubia/nx609j/proprietary/lib/libwfdmmsink.so:system/lib/libwfdmmsink.so \
    vendor/nubia/nx609j/proprietary/lib/libwfdmmsrc.so:system/lib/libwfdmmsrc.so \
    vendor/nubia/nx609j/proprietary/lib/libwfdnative.so:system/lib/libwfdnative.so \
    vendor/nubia/nx609j/proprietary/lib/libwfdrtsp.so:system/lib/libwfdrtsp.so \
    vendor/nubia/nx609j/proprietary/lib/libwfdservice.so:system/lib/libwfdservice.so \
    vendor/nubia/nx609j/proprietary/lib/libwfdsm.so:system/lib/libwfdsm.so \
    vendor/nubia/nx609j/proprietary/lib/libwfduibcinterface.so:system/lib/libwfduibcinterface.so \
    vendor/nubia/nx609j/proprietary/lib/libwfduibcsink.so:system/lib/libwfduibcsink.so \
    vendor/nubia/nx609j/proprietary/lib/libwfduibcsinkinterface.so:system/lib/libwfduibcsinkinterface.so \
    vendor/nubia/nx609j/proprietary/lib/libwfduibcsrc.so:system/lib/libwfduibcsrc.so \
    vendor/nubia/nx609j/proprietary/lib/libwfduibcsrcinterface.so:system/lib/libwfduibcsrcinterface.so \
    vendor/nubia/nx609j/proprietary/lib/rfsa/adsp/libapps_mem_heap.so:system/lib/rfsa/adsp/libapps_mem_heap.so \
    vendor/nubia/nx609j/proprietary/lib/rfsa/adsp/libdspCV_skel.so:system/lib/rfsa/adsp/libdspCV_skel.so \
    vendor/nubia/nx609j/proprietary/lib/rfsa/adsp/libfastcvadsp.so:system/lib/rfsa/adsp/libfastcvadsp.so \
    vendor/nubia/nx609j/proprietary/lib/rfsa/adsp/libfastcvadsp_skel.so:system/lib/rfsa/adsp/libfastcvadsp_skel.so \
    vendor/nubia/nx609j/proprietary/lib/rfsa/adsp/libhvxMathVIO.so:system/lib/rfsa/adsp/libhvxMathVIO.so \
    vendor/nubia/nx609j/proprietary/lib/rfsa/adsp/libqvr_adsp_driver_skel.so:system/lib/rfsa/adsp/libqvr_adsp_driver_skel.so \
    vendor/nubia/nx609j/proprietary/lib/rfsa/adsp/libscveBlobDescriptor_skel.so:system/lib/rfsa/adsp/libscveBlobDescriptor_skel.so \
    vendor/nubia/nx609j/proprietary/lib/rfsa/adsp/libscveFaceLandmark_skel.so:system/lib/rfsa/adsp/libscveFaceLandmark_skel.so \
    vendor/nubia/nx609j/proprietary/lib/rfsa/adsp/libscveT2T_skel.so:system/lib/rfsa/adsp/libscveT2T_skel.so \
    vendor/nubia/nx609j/proprietary/lib/rfsa/adsp/libsns_low_lat_stream_skel.so:system/lib/rfsa/adsp/libsns_low_lat_stream_skel.so \
    vendor/nubia/nx609j/proprietary/lib/sensors.hal.tof.so:system/lib/sensors.hal.tof.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.esepowermanager@1.0.so:system/lib/vendor.qti.esepowermanager@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.gnss@1.0.so:system/lib/vendor.qti.gnss@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.camera.device@1.0.so:system/lib/vendor.qti.hardware.camera.device@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.data.latency@1.0.so:system/lib/vendor.qti.hardware.data.latency@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.factory@1.0.so:system/lib/vendor.qti.hardware.factory@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.fm@1.0.so:system/lib/vendor.qti.hardware.fm@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.iop@1.0.so:system/lib/vendor.qti.hardware.iop@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.iop@2.0.so:system/lib/vendor.qti.hardware.iop@2.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.limits@1.0.so:system/lib/vendor.qti.hardware.limits@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.perf@1.0.so:system/lib/vendor.qti.hardware.perf@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.qdutils_disp@1.0.so:system/lib/vendor.qti.hardware.qdutils_disp@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.qteeconnector@1.0.so:system/lib/vendor.qti.hardware.qteeconnector@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.tui_comm@1.0.so:system/lib/vendor.qti.hardware.tui_comm@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.vpp@1.1.so:system/lib/vendor.qti.hardware.vpp@1.1.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.hardware.wigig.netperftuner@1.0.so:system/lib/vendor.qti.hardware.wigig.netperftuner@1.0.so \
    vendor/nubia/nx609j/proprietary/lib/vendor.qti.imsrtpservice@1.0.so:system/lib/vendor.qti.imsrtpservice@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/com.qualcomm.qti.ant@1.0.so:system/lib64/com.qualcomm.qti.ant@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/com.qualcomm.qti.bluetooth_audio@1.0.so:system/lib64/com.qualcomm.qti.bluetooth_audio@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/com.qualcomm.qti.imscmservice@1.0.so:system/lib64/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/com.qualcomm.qti.imscmservice@1.1.so:system/lib64/com.qualcomm.qti.imscmservice@1.1.so \
    vendor/nubia/nx609j/proprietary/lib64/com.qualcomm.qti.wifidisplayhal@1.0.so:system/lib64/com.qualcomm.qti.wifidisplayhal@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/hw/sensors.msm8998.so:system/lib64/hw/sensors.msm8998.so \
    vendor/nubia/nx609j/proprietary/lib64/lib-imscamera.so:system/lib64/lib-imscamera.so \
    vendor/nubia/nx609j/proprietary/lib64/lib-imsvideocodec.so:system/lib64/lib-imsvideocodec.so \
    vendor/nubia/nx609j/proprietary/lib64/lib-imsvt.so:system/lib64/lib-imsvt.so \
    vendor/nubia/nx609j/proprietary/lib64/lib-imsvtextutils.so:system/lib64/lib-imsvtextutils.so \
    vendor/nubia/nx609j/proprietary/lib64/lib-imsvtutils.so:system/lib64/lib-imsvtutils.so \
    vendor/nubia/nx609j/proprietary/lib64/libNubiaImageAlgorithm.so:system/lib64/libNubiaImageAlgorithm.so \
    vendor/nubia/nx609j/proprietary/lib64/libantradio.so:system/lib64/libantradio.so \
    vendor/nubia/nx609j/proprietary/lib64/libarcsoft_beautyshot.so:system/lib64/libarcsoft_beautyshot.so \
    vendor/nubia/nx609j/proprietary/lib64/libarcsoft_beautyshot_image_algorithm.so:system/lib64/libarcsoft_beautyshot_image_algorithm.so \
    vendor/nubia/nx609j/proprietary/lib64/libarcsoft_beautyshot_video_algorithm.so:system/lib64/libarcsoft_beautyshot_video_algorithm.so \
    vendor/nubia/nx609j/proprietary/lib64/libarcsoft_low_light_shot.so:system/lib64/libarcsoft_low_light_shot.so \
    vendor/nubia/nx609j/proprietary/lib64/libarcsoft_night_shot.so:system/lib64/libarcsoft_night_shot.so \
    vendor/nubia/nx609j/proprietary/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/nubia/nx609j/proprietary/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/nubia/nx609j/proprietary/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/nubia/nx609j/proprietary/lib64/liblocationservice_jni.so:system/lib64/liblocationservice_jni.so \
    vendor/nubia/nx609j/proprietary/lib64/libmiracast.so:system/lib64/libmiracast.so \
    vendor/nubia/nx609j/proprietary/lib64/libmmcamera_faceproc.so:system/lib64/libmmcamera_faceproc.so \
    vendor/nubia/nx609j/proprietary/lib64/libmmcamera_faceproc2.so:system/lib64/libmmcamera_faceproc2.so \
    vendor/nubia/nx609j/proprietary/lib64/libnubia_clone.so:system/lib64/libnubia_clone.so \
    vendor/nubia/nx609j/proprietary/lib64/libnubia_delay_recorder.so:system/lib64/libnubia_delay_recorder.so \
    vendor/nubia/nx609j/proprietary/lib64/libnubia_effect.so:system/lib64/libnubia_effect.so \
    vendor/nubia/nx609j/proprietary/lib64/libnubia_media_player.so:system/lib64/libnubia_media_player.so \
    vendor/nubia/nx609j/proprietary/lib64/libnubia_trajectory.so:system/lib64/libnubia_trajectory.so \
    vendor/nubia/nx609j/proprietary/lib64/libnubiajpeg.so:system/lib64/libnubiajpeg.so \
    vendor/nubia/nx609j/proprietary/lib64/libqdMetaData.system.so:system/lib64/libqdMetaData.system.so \
    vendor/nubia/nx609j/proprietary/lib64/libqti-at.so:system/lib64/libqti-at.so \
    vendor/nubia/nx609j/proprietary/lib64/libqti-perfd-client_system.so:system/lib64/libqti-perfd-client_system.so \
    vendor/nubia/nx609j/proprietary/lib64/libqti-util_system.so:system/lib64/libqti-util_system.so \
    vendor/nubia/nx609j/proprietary/lib64/libqti_performance.so:system/lib64/libqti_performance.so \
    vendor/nubia/nx609j/proprietary/lib64/librcc.so:system/lib64/librcc.so \
    vendor/nubia/nx609j/proprietary/lib64/libsdm-disp-apis.so:system/lib64/libsdm-disp-apis.so \
    vendor/nubia/nx609j/proprietary/lib64/libsensor1.so:system/lib64/libsensor1.so \
    vendor/nubia/nx609j/proprietary/lib64/libsensor_reg.so:system/lib64/libsensor_reg.so \
    vendor/nubia/nx609j/proprietary/lib64/libstagefright_soft_qtiflacdec.so:system/lib64/libstagefright_soft_qtiflacdec.so \
    vendor/nubia/nx609j/proprietary/lib64/libtrueportrait.so:system/lib64/libtrueportrait.so \
    vendor/nubia/nx609j/proprietary/lib64/libtruescanner.so:system/lib64/libtruescanner.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfdavenhancements.so:system/lib64/libwfdavenhancements.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfdcodecv4l2.so:system/lib64/libwfdcodecv4l2.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfdcommonutils.so:system/lib64/libwfdcommonutils.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfdconfigutils.so:system/lib64/libwfdconfigutils.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfdmminterface.so:system/lib64/libwfdmminterface.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfdmmsink.so:system/lib64/libwfdmmsink.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfdmmsrc.so:system/lib64/libwfdmmsrc.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfdnative.so:system/lib64/libwfdnative.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfdrtsp.so:system/lib64/libwfdrtsp.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfds.so:system/lib64/libwfds.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfdservice.so:system/lib64/libwfdservice.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfdsm.so:system/lib64/libwfdsm.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfduibcinterface.so:system/lib64/libwfduibcinterface.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfduibcsink.so:system/lib64/libwfduibcsink.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfduibcsinkinterface.so:system/lib64/libwfduibcsinkinterface.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfduibcsrc.so:system/lib64/libwfduibcsrc.so \
    vendor/nubia/nx609j/proprietary/lib64/libwfduibcsrcinterface.so:system/lib64/libwfduibcsrcinterface.so \
    vendor/nubia/nx609j/proprietary/lib64/sensors.hal.tof.so:system/lib64/sensors.hal.tof.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.esepowermanager@1.0.so:system/lib64/vendor.qti.esepowermanager@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.gnss@1.0.so:system/lib64/vendor.qti.gnss@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.camera.device@1.0.so:system/lib64/vendor.qti.hardware.camera.device@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.data.latency@1.0.so:system/lib64/vendor.qti.hardware.data.latency@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.factory@1.0.so:system/lib64/vendor.qti.hardware.factory@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.fm@1.0.so:system/lib64/vendor.qti.hardware.fm@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.iop@1.0.so:system/lib64/vendor.qti.hardware.iop@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.iop@2.0.so:system/lib64/vendor.qti.hardware.iop@2.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.limits@1.0.so:system/lib64/vendor.qti.hardware.limits@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.perf@1.0.so:system/lib64/vendor.qti.hardware.perf@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.qdutils_disp@1.0.so:system/lib64/vendor.qti.hardware.qdutils_disp@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.qteeconnector@1.0.so:system/lib64/vendor.qti.hardware.qteeconnector@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.tui_comm@1.0.so:system/lib64/vendor.qti.hardware.tui_comm@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.vpp@1.1.so:system/lib64/vendor.qti.hardware.vpp@1.1.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.hardware.wigig.netperftuner@1.0.so:system/lib64/vendor.qti.hardware.wigig.netperftuner@1.0.so \
    vendor/nubia/nx609j/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:system/lib64/vendor.qti.imsrtpservice@1.0.so

PRODUCT_PACKAGES += \
    com.qti.location.sdk \
    com.qti.snapdragon.sdk.display \
    vendor.qti.hardware.fingerprint-V1.0-java

ifeq ($(QCPATH),)

PRODUCT_PACKAGES += \
    AntHalService \
    QtiSystemService \
    QtiTelephonyService \
    WfdService \
    embms \
    ims \
    imssettings \
    CNEService \
    com.qualcomm.location \
    dpmserviceapp \
    qcrilmsgtunnel \
    QtiTelephonyServicelibrary \
    WfdCommon \
    com.qti.dpmframework \
    qcnvitems \
    qcrilhook \
    qti-telephony-common
endif

-include vendor/extra/devices.mk
ifneq ($(call is-qc-perf-target),true)
endif
